site_name: Vexy PDF Werk
site_url: https://vexyart.github.io/vexy-pdf-werk/
repo_url: https://github.com/vexyart/vexy-pdf-werk/
docs_dir: src_docs
site_dir: docs
use_directory_urls: true

theme:
  name: material
  features:
    - navigation.prune
    - toc.integrate

nav:
  - Home: 'index.md'
  - 'Getting Started':
    - 'Installation': '01-getting-started/00-installation.md'
    - 'Quick Start': '01-getting-started/01-quick-start.md'
  - 'User Guide':
    - 'CLI Usage': '02-user-guide/00-cli-usage.md'
    - 'Configuration': '02-user-guide/01-configuration.md'
    - 'Output Formats': '02-user-guide/02-output-formats.md'
  - 'API Reference':
    - 'Index': '03-api-reference/00-index.md'
    - 'Core Components': '03-api-reference/01-core-components.md'
    - 'Integrations': '03-api-reference/02-integrations.md'
    - 'Utilities': '03-api-reference/03-utilities.md'
  - 'Specification':
    - 'Introduction and Architecture': '04-specification/00-introduction-and-architecture.md'
    - 'Technology Stack and Configuration': '04-specification/01-technology-stack-and-configuration.md'
    - 'Integration Points and Error Handling': '04-specification/02-integration-points-and-error-handling.md'
    - 'Security, Performance, and Quality': '04-specification/03-security-performance-and-quality.md'
    - 'Extensibility and Success Criteria': '04-specification/04-extensibility-and-success-criteria.md'
  - 'Development':
    - 'Contributing': '05-development/00-contributing.md'
    - 'Testing': '05-development/01-testing.md'
    - 'Release Process': '05-development/02-release-process.md'
